### ISSUE TITLE
Install Method?

### ISSUE THREAD

**Issue by atomoton** [StruBE-KAUST/pymolOSVR#1]
What is the best way to install this in Pymol?

I have the OSVR installed I think, but I specifically mean this plugin. Do I clone it and then import a specific .py file as a plugin in pymol?

Thanks!

**Comment by StruBE-KAUST** [comment]
Hi atomoton,

One way to install the plugin is to create an archive file (.tar.gz) from the whole directory, then import it in PyMol as a plugin.
One other way (better in my opinion because you can easy update pymolOSVR) is to create a symlink (ln -s) in the pymol plugins directory (which should be ~/.pymol/startup) to the project root directory.

Let me know if it works for you. If yes, I'll write a README.md.

**Comment by atomoton** [comment]
Tried both methods, but I get this error with each:
Unable to initialize plugin 'pymolOSVR' (pmg_tk.startup.pymolOSVR).

I'm running PyMol opensource 1.7.x on Ubuntu

**Comment by StruBE-KAUST** [comment]
This is a very generic error when an exception is raised inside a plugin.

In the repo, you can find a track.py file. Could you try to execute this python script to see if the interface between the OSVR and Python works ? The display of this script does not matter (two grids showing the spatial position of the headset). I just want to know if the script works.

**Comment by atomoton** [comment]
Here is the error. Looks like OSVR is not set up properly?

```
→ ./track.py 
Traceback (most recent call last):
  File "./track.py", line 2, in <module>
    import osvr.ClientKit
  File "/home/andrew/pymolOSVR/osvr/ClientKit.py", line 1, in <module>
    from ClientKitRaw import *
  File "/home/andrew/pymolOSVR/osvr/ClientKitRaw.py", line 8, in <module>
    mylib = cdll.LoadLibrary("libosvrClientKit.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libosvrClientKit.so: cannot open shared object file: No such file or directory
```

**Comment by StruBE-KAUST** [comment]
In your OSVR installation directory (which could be different of the repository directory if you used the CMAKE_INSTALL_PREFIX flag), you should have a lib/ directory. Add this dir to the LD_LIBRARY_PATH variable, and export it :
```LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/path/to/osvr/lib"
export LD_LIBRARY_PATH```
Then try again.

If it works, you can add these two lines to your ~/.profile file.

And BTW, before using track.py, `git pull` the repository. I fixed an issue which made impossible to stop the script.

**Comment by atomoton** [comment]
So far so good, track.py seems to load, this is what I get:
```
→ ./track.py 
Nov 17 11:51:00.798 info [OSVR]: 0x7ff33cd2916b/usr/bin/python2.7
Nov 17 11:51:00.798 info [OSVR: com.dunatotatos.pymol.osvr]: OSVR client context initialized for com.dunatotatos.pymol.osvr
Nov 17 11:51:02.002 info [OSVR: com.dunatotatos.pymol.osvr]: Could not connect to OSVR server in the timeout period allotted of 200ms
Nov 17 11:51:02.003 info [OSVR]: /home/andrew/osvr-core-ubuntu-build-script/OSVR-Core/src/osvr/Common/ClientInterface.cpp:38: Interface initialized for /me/head
Nov 17 11:51:02.003 info [OSVR: com.dunatotatos.pymol.osvr]: Could not resolve source for /me/head

```

However, the pymol plugin still doesn't initialize.

**Comment by atomoton** [comment]
I am able to run the OSVR server I think:

`→ ./osvr_server 
Nov 17 11:58:03.913 info [OSVR]: 0x7f07b29bd16b/home/andrew/osvr-core-ubuntu-build-script/dist/bin/osvr_server
Nov 17 11:58:03.913 info [OSVR Server]: Using default config file - pass a filename on the command line to use a different one.
Nov 17 11:58:03.913 info [OSVR Server]: Using config file 'osvr_server_config.json'.
Nov 17 11:58:03.913 info [OSVR Server]: Constructing server as configured...
Nov 17 11:58:03.914 info [OSVR Server]: Loading auto-loadable plugins...
Nov 17 11:58:04.014 info [OSVR Server]: Loading plugins...
Nov 17 11:58:04.014 info [OSVR Server]: Instantiating configured drivers...
Nov 17 11:58:04.014 info [OSVR Server]: Using OSVR HDK for display configuration. Did not find an alternate valid 'display' object in config file.
Nov 17 11:58:04.014 info [OSVR Server]: Triggering automatic hardware detection...
Nov 17 11:58:04.014 info [OSVR Server]: Registering shutdown handler...
Nov 17 11:58:04.014 info [OSVR Server]: Starting server mainloop: OSVR Server is ready to go!
Nov 17 11:58:04.015 info [OSVR Server]: Performing hardware auto-detection.
`

**Comment by StruBE-KAUST** [comment]
The track output looks like the OSVR server does not run as expected.

Is `Nov 17 11:58:04.015 info [OSVR Server]: Performing hardware auto-detection.`
the last line of the osrvr_server output? Some steps are missing, like the result of the auto-detection or the calibration. I obtain this line as a last line when I forget to plug the headset.

Is sounds a bit silly, but did you check that all cables were plugged in? Which headset do you use?

**Comment by atomoton** [comment]
Not silly at all, as I really did have nothing plugged in. I am planning to use Google Cardboard, I don't own any other headsets.

**Comment by StruBE-KAUST** [comment]
I do not know how to use the Google Cardboard, but it does not look like something you can plug on your computer. It looks more like a system which needs a standalone application on your smartphone.

OSVR is Android compatible : https://github.com/OSVR/OSVR-Android-Build
This means the Google Cardboard could work with pymolOSVR, with at a very little condition : making PyMol run on your smartphone. And I have absolutely no idea how to do that. I seriously doubt it can be reasonably achieved.

Sorry...

**Comment by Ishihito** [comment]
Hi, I've been trying to install this as well so I can get PyMOL to work with the VIVE, however I've been getting an annoying error code 105 when trying to start the OSVR server. 
I am running version 1516665106 of SteamVR; an OSVR-Vive plugin build 73; HDK version 0.8 (also tried the OSVR runtime version  0.6.2118-gd690c5ef  but getting same errors). This is the server log:
[log.log](https://github.com/StruBE-KAUST/pymolOSVR/files/1662506/log.log)
The vive is otherwise functioning fine and I can actually see the extended screen in 3D and is working perfectly fine within Steam.

**Comment by dunatotatos** [comment]
Hi @Ishihito ,

Thank you for your message.

This project is now obsolete. We switched to another technology named A-Frame which makes VR compatible with any VR headset in a much easier way. You can find the github repository [here](https://github.com/StruBE-KAUST/django-proteinviewer). It is a pain to install, and the application does not work properly, but we are still working on it.

Best,
Duna
